#!/bin/bash

sysctl -w net.core.somaxconn=1024

service mysql start
rabbitmq-server -detached
rabbitmq-plugins enable rabbitmq_management
wget http://localhost:15672/cli/rabbitmqadmin -O /usr/local/bin/rabbitmqadmin
chmod a+x /usr/local/bin/rabbitmqadmin

python setup.py init
nginx -p . -c conf/htm-it-api.conf
supervisord -c conf/supervisord.conf
